# .Synopsis
#     Spoke Deployment pipeline

# .NOTES
#     Author     : Roman Rabodzei
#     Version    : 1.0.230707
#
#             _
#         .__(.)<  (MEOW)
#          \___)
#  ~~~~~~~~~~~~~~~~~~~~~~~~

name: 
  '${{parameters.CustomerCode}}_${{parameters.Subscription}}_Spoke_$(Location)_1.0.0$(Rev:.r)'

trigger: 
  none

pr:
  none

parameters:
  - name: CustomerCode
    displayName: Specify Customer Code
    type: string

  - name: Subscription
    displayName: Specify Subscription (HUB / DEVTEST / ACC / PROD)
    type: string

  - name: networkingTemplate
    displayName: Workload Network Deployment
    type: boolean
    default: true
    values:
      - true
      - false

  - name: vaultTemplate
    displayName: Workload Vault Deployment
    type: boolean
    default: false
    values:
      - true
      - false

variables:
  - group: "${{ parameters.CustomerCode }}-${{ parameters.Subscription }} Infra"

pool:
  vmImage: windows-latest

stages:
- stage: Checking_Templates
  displayName: Checking Templates
  variables:
    - group: "${{ parameters.CustomerCode }}-${{ parameters.Subscription }} Infra"
  jobs:
  - job: Checking_Templates
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 360
    displayName: Checking Templates
    steps:
      - task: PowerShell@2
        displayName: Agent IP
        enabled: true
        inputs:
          targetType: "inline"
          script: |
            $hostIp = (Invoke-WebRequest http://ipv4.icanhazip.com).Content
            Write-Host "`nAgent Public IP:"
            Write-Host "##[section]$hostIp"
          pwsh: true
          workingDirectory: "$(system.defaultWorkingDirectory)"
          
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: Replacing Variables
        enabled: true
        inputs:
          rootDirectory: "$(system.defaultWorkingDirectory)"
          targetFiles: "**/*.json"
          encoding: "auto"
          writeBOM: true
          verbosity: "detailed"
          actionOnMissing: "continue"
          keepToken: false
          tokenPrefix: "#{"
          tokenSuffix: "}#"

      - ${{ if eq( parameters['networkingTemplate'], 'true') }}:
        - task: PowerShell@2
          name: RunLinterNetwork
          displayName: Running Bicep linter (Networking template)
          enabled: true
          inputs:
            targetType: "inline"
            script: |
                az bicep build --file './2 Layers/networking.bicep'
            pwsh: true
            workingDirectory: "$(system.defaultWorkingDirectory)"

        - task: AzureCLI@2
          name: RunPreflightValidationNetwork
          displayName: Running preflight validation (Networking template)
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment sub validate --name '$(Build.BuildNumber)' --location "$(location)".ToLower() --template-file './2 Layers/networking.bicep' --parameters networkingTemplate=${{parameters.networkingTemplate}} guid=$(customerAttributionGuid) subscription=$(subscription)
            workingDirectory: "$(system.defaultWorkingDirectory)"

        - task: AzureCLI@2
          name: RunWhatIfNetwork
          displayName: Previewing Azure changes (Networking template)
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment sub what-if --name '$(Build.BuildNumber)' --location "$(location)".ToLower() --template-file './2 Layers/networking.bicep' --parameters networkingTemplate=${{parameters.networkingTemplate}} guid=$(customerAttributionGuid) subscription=$(subscription)
            workingDirectory: "$(system.defaultWorkingDirectory)"

      - ${{ if eq( parameters['vaultTemplate'], 'true') }}:
        - task: PowerShell@2
          name: RunLinterVault
          displayName: Running Bicep linter (Vault template)
          enabled: true
          inputs:
            targetType: "inline"
            script: |
                az bicep build --file './2 Layers/vault.bicep'
            pwsh: true
            workingDirectory: "$(system.defaultWorkingDirectory)"

        - task: AzureCLI@2
          name: RunPreflightValidationvault
          displayName: Running preflight validation (Vault template)
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment sub validate --name '$(Build.BuildNumber)' --location "$(location)".ToLower() --template-file './2 Layers/vault.bicep' --parameters vaultTemplate=${{parameters.vaultTemplate}} guid=$(customerAttributionGuid) subscription=$(subscription)
            workingDirectory: "$(system.defaultWorkingDirectory)"

        - task: AzureCLI@2
          name: RunWhatIfVault
          displayName: Previewing Azure changes (Vault template)
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment sub what-if --name '$(Build.BuildNumber)' --location "$(location)".ToLower() --template-file './2 Layers/vault.bicep' --parameters vaultTemplate=${{parameters.vaultTemplate}} guid=$(customerAttributionGuid) subscription=$(subscription)
            workingDirectory: "$(system.defaultWorkingDirectory)"

- stage: Deploying_Infractructure
  displayName: Deploying Infractructure
  variables:
  - group: "${{ parameters.CustomerCode }}-${{ parameters.Subscription }} Infra"
  jobs:
  - deployment: Deploy
    environment: ${{parameters.environment}}-IaC
  - job: Deploying_Infractructure
    displayName: Deploying Environment
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 360
    continueOnError: true
    strategy:
      runOnce:
        deploy:
    steps:
      - checkout: self
      - task: PowerShell@2
        displayName: Agent IP
        enabled: true
        inputs:
          targetType: "inline"
          script: |
            $hostIp = (Invoke-WebRequest http://ipv4.icanhazip.com).Content
            Write-Host "`nAgent Public IP:"
            Write-Host "##[section]$hostIp"
          pwsh: true
          workingDirectory: "$(system.defaultWorkingDirectory)"

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: Replacing Variables
        continueOnError: true
        enabled: true
        inputs:
          rootDirectory: "$(system.defaultWorkingDirectory)"
          targetFiles: "**/*.json"
          encoding: "auto"
          writeBOM: true
          verbosity: "detailed"
          actionOnMissing: "continue"
          keepToken: false
          tokenPrefix: "#{"
          tokenSuffix: "}#"

      - ${{ if eq( parameters['networkingTemplate'], 'true') }}:
        - task: AzureCLI@2
          name: DeployBicepFileNetwork
          displayName: Deploying Bicep Templates
          continueOnError: true
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment sub create --name '$(Build.BuildNumber)' --location "$(location)".ToLower() --template-file './2 Layers/networking.bicep' --parameters networkingTemplate=${{parameters.networkingTemplate}} guid=$(customerAttributionGuid) subscription=$(subscription)
            workingDirectory: '$(system.defaultWorkingDirectory)'

      - ${{ if eq( parameters['vaultTemplate'], 'true') }}:
        - task: AzureCLI@2
          name: DeployBicepFileVault
          displayName: Deploying Bicep Templates
          continueOnError: true
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment sub create --name '$(Build.BuildNumber)' --location "$(location)".ToLower() --template-file './2 Layers/vault.bicep' --parameters vaultTemplate=${{parameters.vaultTemplate}} guid=$(customerAttributionGuid) subscription=$(subscription)
            workingDirectory: '$(system.defaultWorkingDirectory)'
